// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeBhq5ux8JF0CBRvDIgdyQYnA5hbfLvjw',
    appId: '1:538763677400:android:eb9d46a7259501d84591ad',
    messagingSenderId: '538763677400',
    projectId: 'scorecaddie-1e9e0',
    storageBucket: 'scorecaddie-1e9e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqsY8pjAp-AuXXmGV21aVZtIFkJi7HVmc',
    appId: '1:538763677400:ios:a0378825865fc26c4591ad',
    messagingSenderId: '538763677400',
    projectId: 'scorecaddie-1e9e0',
    storageBucket: 'scorecaddie-1e9e0.firebasestorage.app',
    iosClientId: '538763677400-h2re3dmdbft7qkcp9b2t4ah96k8rhea9.apps.googleusercontent.com',
    iosBundleId: 'com.scorecaddie.scoreCaddie',
  );
}
