// The ScoreCaddie achievement set: the app's 56, re-voiced, plus the ones the
// new features earn. ids of existing achievements are unchanged.
export const TIER = { bronze: '#D08A4E', silver: '#D9E0D4', gold: '#F5C531' };

// [id, title, description, category, points, shape, colour or tier, isNew]
export const CATALOG = [
  // Scoring
  ['score_100', 'Century Club', 'Break 100 for the first time.', 'scoring', 20, 'trophy', 'bronze'],
  ['score_90', 'Breaking 90', 'Break 90 for the first time.', 'scoring', 50, 'trophy', 'silver'],
  ['score_80', 'Elite 80', 'Break 80 for the first time.', 'scoring', 100, 'trophy', 'gold'],
  ['birdie_first', 'First Flight', 'Make your first birdie.', 'scoring', 10, 'birdie', '#7DD3FC'],
  ['eagle_first', 'Soaring Eagle', 'Make your first eagle.', 'scoring', 100, 'eagle', '#C98A4B'],
  ['albatross', 'The Double Eagle', 'Make an albatross: three under on one hole.', 'scoring', 1000, 'albatross', '#EEF2F5'],
  ['hole_in_one', 'The Miracle', 'Make a hole in one.', 'scoring', 500, 'gem', '#5EEAD4'],
  ['par_4_eagle', 'Driver Master', 'Make an eagle on a par 4.', 'scoring', 300, 'driver', '#6D8CF5'],
  ['par_master', 'Par Machine', 'Make nine or more pars in one round.', 'scoring', 50, 'cog', '#9FB3C8'],
  ['bogey_free', 'Perfectly Clean', 'Finish a round without a bogey.', 'scoring', 200, 'sparkle', '#E6F99D'],
  ['sub_par_9', 'Sub-Par Nine', 'Finish the front or back nine under par.', 'scoring', 100, 'minus', '#F26B6B'],
  ['long_drive', 'Bomber', 'Hit a drive over 300 yards.', 'scoring', 10, 'rocket', '#F97316'],
  // Consistency
  ['streak_par_3', 'Par Streak', 'Make three pars in a row.', 'consistency', 10, 'caterpillar', '#84CC16'],
  ['lucky_7', 'Lucky 7', 'Make seven pars in a row.', 'consistency', 77, 'horseshoe', '#C9D1D9'],
  ['streak_birdie_2', 'Back-to-Back', 'Make birdies on two holes in a row.', 'consistency', 50, 'birdie', 'silver'],
  ['streak_birdie_3', 'Turkey!', 'Make birdies on three holes in a row.', 'consistency', 150, 'turkey', '#C2703D'],
  ['fairway_king', 'Fairway King', 'Hit every fairway in a round.', 'consistency', 50, 'king', '#A3E635'],
  ['gir_master', 'GIR Master', 'Hit 12 or more greens in regulation.', 'consistency', 50, 'flag', '#86EFAC'],
  ['scrambler', 'Scrambler', 'Save par from a bunker.', 'consistency', 10, 'shovel', '#E9C46A'],
  ['sand_save_first', 'Beach Pro', 'Get up and down from a bunker for the first time.', 'consistency', 10, 'palm', '#34D399'],
  ['no_penalties', 'Disciplined', 'Finish a full round without a penalty stroke.', 'consistency', 30, 'shield', '#60A5FA'],
  ['putt_pro', 'Putt Pro', 'Take fewer than 30 putts in a round.', 'consistency', 40, 'mallet', 'silver'],
  ['sub_30_putts', 'Putting Wizard', 'Take 25 putts or fewer in a round.', 'consistency', 200, 'mallet', 'gold'],
  ['comeback', 'Relentless', 'Score 10 or more shots better on the back nine than the front.', 'consistency', 10, 'boomerang', '#FB923C'],
  ['bogey_free_start', 'Never Give Up', 'Break 90 after starting with a triple bogey.', 'consistency', 10, 'glove', '#EF4444'],
  ['streak_week_1', 'Ignition', 'Start your first weekly streak.', 'consistency', 10, 'flame', '#FB923C'],
  ['streak_week_4', 'Monthly Regular', 'Play every week for 4 weeks.', 'consistency', 50, 'flame', 'bronze'],
  ['streak_week_12', 'Committed Golfer', 'Play every week for 12 weeks.', 'consistency', 150, 'flame', 'silver'],
  ['streak_week_26', 'Half Year Hustler', 'Play every week for 26 weeks.', 'consistency', 500, 'flame', 'gold'],
  ['streak_week_52', 'Iron Man', 'Play every week for a whole year.', 'consistency', 1000, 'iron', '#8FA3B5'],
  // Activity
  ['round_1', 'First Dance', 'Finish your first 18-hole round.', 'activity', 10, 'tee', '#F4F7F2'],
  ['round_10', 'Deep Roots', 'Finish 10 rounds.', 'activity', 50, 'acacia', '#65A30D'],
  ['round_50', 'Half-Century', 'Finish 50 rounds.', 'activity', 100, 'medal', 'silver'],
  ['round_100', 'Legendary Status', 'Finish 100 rounds.', 'activity', 500, 'crown', 'gold'],
  ['weekend_warrior', 'Weekend Warrior', 'Play on a Saturday and the Sunday after it.', 'activity', 10, 'calendar', '#F87171'],
  ['early_bird', 'Early Bird', 'Tee off before 7:00.', 'activity', 10, 'sunrise', '#FBBF24'],
  ['night_owl', 'Night Owl', 'Finish a round after 18:30.', 'activity', 10, 'owl', '#8B7CF6'],
  ['marathon', '36-Hole Marathon', 'Play 36 holes in one day.', 'activity', 100, 'sneaker', '#38BDF8'],
  ['lost_ball_zero', 'Ball Saver', 'Finish a round without losing a ball.', 'activity', 10, 'padlock', '#2DD4BF'],
  ['rain_man', 'Rain Man', 'Finish a round in the rain.', 'activity', 10, 'umbrella', '#818CF8'],
  ['winter_golf', 'Cold-Blooded', 'Play a round below 15°C.', 'activity', 10, 'snowflake', '#BAE6FD'],
  ['new_bag', 'Fully Loaded', 'Put 14 clubs in your digital bag.', 'activity', 10, 'bag', '#4F7DF3'],
  ['birthday_golf', 'Gift to Self', 'Play a round on your birthday.', 'activity', 10, 'gift', '#F472B6'],
  ['streak_30_days', 'Dedicated', 'Play at least one round a month, three months running.', 'activity', 100, 'hourglass', '#E0A36A'],
  ['caddie_helper', 'App Guru', 'Open ScoreCaddie 30 days in a row.', 'activity', 10, 'phone', '#E2E8F0'],
  // Explorer
  ['course_5', 'Traveller', 'Play five different courses.', 'explorer', 50, 'pin', 'silver'],
  ['course_10', 'Adventurer', 'Play ten different courses.', 'explorer', 100, 'pin', 'gold'],
  ['kenya_5', 'Kenyan Pride', 'Play five courses in Kenya.', 'explorer', 50, 'maasai', '#D94141'],
  ['links_master', 'Links Master', 'Play a round on a links course.', 'explorer', 10, 'lighthouse', '#FCA5A5'],
  ['altitude_golfer', 'High Flyer', 'Play a round more than 2,000 m above sea level.', 'explorer', 10, 'mountain', '#94A9C7'],
  ['vacation_golf', 'Holiday Swings', 'Play a course away from home while on holiday.', 'explorer', 10, 'suitcase', '#C084FC'],
  // Social
  ['friend_first', 'Social Butterfly', 'Add your first friend.', 'social', 10, 'butterfly', '#C4B5FD'],
  ['friend_round', 'Team Play', 'Play a round with a friend.', 'social', 10, 'hand', '#FDBA74'],
  ['share_10', 'Influencer', 'Share 10 highlight cards.', 'social', 30, 'megaphone', '#FB7185'],
  ['highlight_pro', 'Highlight Pro', 'Make a highlight card for every hole of a round.', 'social', 50, 'camera', '#67E8F9'],
  // New features
  ['voice_100', 'Daniel’s 100', 'Log 100 shots out loud with Daniel.', 'practice', 50, 'mic', '#A3E635', true],
  ['drill_done', 'Homework Done', 'Finish a drill your coach set you.', 'practice', 30, 'cone', '#FF9F43', true],
  ['practice_streak', 'Range Rat', 'Practise three times a week, three weeks running.', 'practice', 100, 'bucket', '#F87171', true],
  ['caddie_first', 'In Good Hands', 'Book your first caddie.', 'social', 20, 'bib', '#FF8266', true],
  ['coach_first', 'Coached Up', 'Take your first lesson with a coach.', 'social', 20, 'cap', '#F5C531', true],
  ['club_join', 'Member', 'Join a club on ScoreCaddie.', 'social', 10, 'clubhouse', '#86EFAC', true],
  ['club_event', 'On the Tee Sheet', 'Enter your first club competition.', 'social', 20, 'ticket', '#F59E0B', true],
  ['scan_card', 'Card Shark', 'Scan a paper scorecard into a round.', 'activity', 10, 'pencil', '#FACC15', true],
  ['hcp_drop', 'Shedding Strokes', 'Bring your handicap index down by a full stroke.', 'scoring', 100, 'leaf', '#4ADE80', true],
].map(([id, title, description, category, points, shape, col, isNew]) => ({
  id, title, description, category, points, shape, isNew: !!isNew,
  tier: TIER[col] ? col : null,
  color: TIER[col] || col,
}));
